### ISSUE TITLE
can't see him, always.

### ISSUE THREAD

**Issue by shisui203** [thebigsmileXD/Spooky#11]
How can I spawn Slendy?

**Comment by inxomnyaa** [comment]
He always spawns at the spawn in the main level. Be sure to not have any entity remover, and any fitting blocks like grass or podzol near the spawn

**Comment by inxomnyaa** [comment]
In the latest PR i changed it to allow any blocks. He will automatically spawn in a specific time period (or always, accordingly to the settings) near the player
