### ISSUE TITLE
Duplicated project on Poggit

### ISSUE THREAD

**Issue by inxomnyaa** [thebigsmileXD/Spooky#15]
![grafik](https://user-images.githubusercontent.com/8733998/66821075-20e0e380-ef42-11e9-8dd6-cdc873f72ac3.png)
@SOF3 is there a way to remove "Spooky" from this? It is not represented in the poggit.yml anymore, but currently it still appears to me. Reason "Spooky" exists is because i once renamed the plugin to Slenderman

**Comment by SOF3** [comment]
If this is a formal request, please create a ticket at https://github.com/poggit/support
