### ISSUE TITLE
Undefined Method 

### ISSUE THREAD

**Issue by Enrick3344** [thebigsmileXD/Spooky#3]
Been getting this error on Getting close to the slenderman.

`[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'Spooky v0.0.0': Call to undefined method xenialdan\Spooky\entities\Slenderman::lookAt() on xenialdan\Spooky\EventListener
[18:17:21] [Server thread/CRITICAL]: Error: "Call to undefined method xenialdan\Spooky\entities\Slenderman::lookAt()" (EXCEPTION) in "myzip://Spooky-master (1).zip#Spooky-master/src/xenialdan/Spooky/EventListener" at line 41`

**Comment by NML32** [comment]
Confirmed, I get the same error.

**Comment by inxomnyaa** [comment]
Update PMMP

**Comment by NML32** [comment]
I'm running the latest version.
PocketMine-MP 1.7dev-344 「[REDACTED]」 implementing API version 3.0.0-ALPHA9 for Minecraft: PE v1.2.0.81 (protocol version 137)

**Comment by inxomnyaa** [comment]
https://github.com/pmmp/PocketMine-MP/search?utf8=✓&q=lookAt&type=
